[build]
builder = "DOCKERFILE"
dockerfilePath = "veksha-web/Dockerfile"
watchPatterns = ["/veksha-web/**", "/veksha-extension/src/popup/**", "/veksha-extension/src/shared/**"]

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 20
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
